version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      
      - run:
          name: "TEST"
          command: . .circleci/build/test.sh


workflows:
  version: 2
  push-workflow:
    jobs:
      - deploy
